arangodb:
  restart: always
  environment:
    ARANGO_ROOT_PASSWORD: ${ARANGO_ROOT_PASSWORD}
  image: arangodb:3.3
  volumes_from:
  - arangodata
  ports:
  - 8529:8529/tcp
  labels:
    io.rancher.container.hostname_override: container_name
arangodata:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
  - /var/lib/arangodb3
  entrypoint: /bin/true
  image: busybox