arangodb:
  restart: always
  environment:
    ARANGO_ROOT_PASSWORD: ${ARANGO_ROOT_PASSWORD}
  image: arangodb/arangodb:3.3.11
  volumes_from:
  - arangodata
  ports:
  - 8529:8529/tcp
  tty: true
  stdin_open: true
arangodata:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
  - /var/lib/arangodb3
  - /var/lib/arangodb3-apps
  entrypoint: /bin/true
  image: busybox