.catalog:
  name: "ArangoDB Community Edition"
  version: "3.3.11"
  description: "ArangoDB running as a single host"
  questions:
    - variable: ARANGO_ROOT_PASSWORD
      description: "ROOT Password"
      label: "ROOT Password"
      type: "string"
      required: true
    - variable: ARANGO_STORAGE_ENGINE
      description: "Storage Engine"
      label: "Storage Engine"
      type: "enum"
      default: mmfiles
      required: true
      options:
        - mmfiles
        - rocksdb
arangodb:
  scale: 1