.catalog:
  name: "ArangoDB Community Edition"
  version: "1.0.0-rancher1"
  description: "ArangoDB running as a single host"
  uuid: arangodb-0
  questions:
    - variable: volume_name
      description: "Name of the volume to store data in"
      label: "Data volume name"
      type: "string"
      required: true
      default: ""
    - variable: ARANGO_ROOT_PASSWORD
      description: "ROOT Password"
      label: "ROOT Password"
      type: "string"
      required: true
arangodb:
  scale: 1