.catalog:
  name: "ArangoDB Community Edition"
  version: "3.3"
  description: "ArangoDB running as a single host"
  uuid: arangodb-0
  questions:
    - variable: ARANGO_ROOT_PASSWORD
      description: "ROOT Password"
      label: "ROOT Password"
      type: "string"
      required: true
arangodb:
  scale: 1